# Generated by Django 5.1.3 on 2025-03-13 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('dropship', 'Dropship'), ('food', 'Food & beverages'), ('clothing', 'Clothing'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Street Address')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complex/Apartment')),
                ('suburb', models.CharField(max_length=100, verbose_name='Suburb')),
                ('city', models.CharField(max_length=100, verbose_name='City/Municipality')),
                ('province', models.CharField(choices=[('GP', 'Gauteng')], max_length=2, verbose_name='Province')),
                ('postal_code', models.CharField(max_length=4, verbose_name='Postal Code')),
                ('country', models.CharField(default='South Africa', max_length=100, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_type', models.CharField(choices=[('residential', 'Residential'), ('business', 'Business'), ('postal', 'Postal'), ('other', 'Other')], default='business', max_length=20, verbose_name='Address Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='seller.businessinformation')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=225, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='seller.businessinformation')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
