# Generated by Django 5.1.3 on 2025-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
    ]
