# Generated by Django 5.1.3 on 2025-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_businessinformation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='registration_number',
            field=models.CharField(max_length=200),
        ),
    ]
