# Generated by Django 5.1.3 on 2025-03-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_businessinformation_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='close_time',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='open_time',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
