# Generated by Django 5.1.3 on 2025-03-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_businessinformation_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
