# Generated by Django 5.1.3 on 2025-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_moderation_is_rejected_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
