# Generated by Django 5.1.3 on 2025-03-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_businessinformation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
