# Generated by Django 5.1.3 on 2025-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.TextField(null=True),
        ),
    ]
