# Generated by Django 5.1.3 on 2025-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_order_orderextra_orderitem_orderaddons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
