# Generated by Django 5.1.3 on 2025-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
