# Generated by Django 5.1.3 on 2025-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_order_business_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('On route', 'On route'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
