# Generated by Django 5.1.3 on 2025-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='account_code',
            field=models.CharField(default='ACCT_dmi9jzou4maimox', max_length=200),
        ),
    ]
