# Generated by Django 5.1.3 on 2025-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0022_businessinformation_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='account_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
