# Generated by Django 5.1.3 on 2025-04-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0024_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=50, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('GP', 'Gauteng')], max_length=100, verbose_name='Province'),
        ),
    ]
