# Generated by Django 5.1.3 on 2025-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0025_alter_address_postal_code_alter_address_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='open_orders',
            field=models.BooleanField(default=False),
        ),
    ]
