# Generated by Django 5.1.3 on 2025-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0027_businessrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='image',
            field=models.ImageField(default='default_business.png', upload_to='uploads/business_images/'),
        ),
    ]
