# Generated by Django 5.1.3 on 2025-05-17 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0028_businessinformation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='businessrating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='moderation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='productmoderation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('plate', 'Plate'), ('kota', 'Kota'), ('dagwood', 'Dagwood'), ('drinks', 'Drinks'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
