# Generated by Django 5.1.3 on 2025-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0029_businessinformation_slug_businessinformation_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
