# Generated by Django 5.1.3 on 2025-05-17 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0030_alter_businessinformation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
    ]
