# Generated by Django 5.1.3 on 2025-05-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0032_alter_product_uuid'),
        ('seller', '0036_auto_20250517_1257'),
    ]

    operations = [
    ]
