# Generated by Django 5.1.3 on 2025-05-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0037_merge_0032_alter_product_uuid_0036_auto_20250517_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrating',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
