# Generated by Django 5.1.3 on 2025-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0039_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drop_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
