# Generated by Django 5.1.3 on 2025-10-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0040_order_drop_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drop_code',
        ),
        migrations.AddField(
            model_name='order',
            name='drop_codes',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
