# Generated by Django 5.1.3 on 2025-10-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0041_remove_order_drop_code_order_drop_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
