# Generated by Django 5.1.3 on 2025-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0042_order_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
