# Generated by Django 5.1.3 on 2025-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0044_alter_addon_timestamp_alter_address_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessinformation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/business_images/"
            ),
        ),
    ]
