# Generated by Django 5.1.3 on 2025-04-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_deliverytransaction_deliverywallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytransaction',
            name='fees',
        ),
        migrations.AddField(
            model_name='deliverytransaction',
            name='order_id',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
