# Generated by Django 5.1.3 on 2025-11-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_businesswallet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
