# Generated by Django 5.1.3 on 2025-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='phone_number',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
