# Generated by Django 5.1.3 on 2025-04-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_courier_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='courier',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='status',
            field=models.CharField(default='pending ', max_length=200),
        ),
    ]
