# Generated by Django 5.1.3 on 2025-04-27 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_remove_courier_is_approved_courier_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
