# Generated by Django 5.1.3 on 2025-04-27 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_courier_created_at'),
        ('seller', '0026_businessinformation_open_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.order'),
        ),
    ]
