# Generated by Django 5.1.3 on 2025-10-29 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_orderdelivery_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
