# Generated by Django 5.1.3 on 2025-03-18 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='extras',
        ),
        migrations.AlterField(
            model_name='cartextra',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='user.cart'),
        ),
    ]
