# Generated by Django 5.1.3 on 2025-03-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_addon'),
        ('user', '0002_remove_cart_extras_alter_cartextra_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.extras')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartAddons', to='user.cart')),
            ],
        ),
    ]
