# Generated by Django 5.1.3 on 2025-03-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_product_small_description'),
        ('user', '0003_cartaddons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaddons',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.addon'),
        ),
        migrations.AlterField(
            model_name='cartaddons',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartAddon', to='user.cart'),
        ),
    ]
