# Generated by Django 5.1.3 on 2025-03-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_orderaddress_notes'),
        ('user', '0008_alter_cartextra_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartextra',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.extras'),
        ),
    ]
