# Generated by Django 5.1.3 on 2025-10-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdeliveryaddress',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
