# Generated by Django 5.1.3 on 2025-10-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_cartdeliveryaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdeliveryaddress',
            name='area',
            field=models.CharField(max_length=51, null=True),
        ),
    ]
