# Generated by Django 5.1.3 on 2025-10-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_cartdeliveryaddress_area'),
    ]

    operations = [
    ]
