# Generated by Django 5.1.3 on 2025-10-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20251031_0002'),
    ]

    operations = [
    ]
