# Generated by Django 5.1.3 on 2025-11-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_cartdeliveryaddress_is_default_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='referralprofile',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
