# Generated by Django 5.1.3 on 2025-11-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_cartdeliveryaddress_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdeliveryaddress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
